# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "rb_sys/extensiontask"

task build: :compile

RbSys::ExtensionTask.new("voicevox_core_ruby_api") do |ext|
  ext.lib_dir = "lib/voicevox_core_ruby_api"
end

task default: %i[compile spec rubocop]
